# dependencies
markdown:           kramdown
highlighter:        pygments
theme:              jekyll-theme-cayman


# Permalinks
permalink:           pretty

# Setup
title:              Jeff Hinzmann           
tagline:            'Developer Portfolio'       
url:                https://jahinzmann.github.io        
baseurl:            /      

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
sass_dir:           _sass
style:              :compressed

# About/contact
author:         
  name:             Jeff Hinzmann            
  url:              https://jahinzmann.github.io       
  email:            JAHinzmann@gmail.com           

# Custom vars
version:             2.0.0
# github:            https://github.com/jahinzmann
  # repo:            https://github.com/jahinzmann/jahinzmann.github.io  

# Gems
# plugins:
#  - jekyll-paginate
#  - jekyll-gist

# theme: jekyll-theme-cayman

